### PR TITLE
Error: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}

### PR DESCRIPTION
**Pull request by djmitche**
https://sentry.io/taskcluster/taskcluster-github/issues/208562878/

```
Error: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}

Error: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
```

### CODE REVIEW

**Comment by djmitche** [comment]
After some timezone futzing:
```
Feb 08 20:52:51 taskcluster-github app/web.1: Thu, 09 Feb 2017 01:52:51 GMT taskcluster-github:api:764bc500-ee6a-11e6-868f-1e43848cab97 Finished Publishing event message on pulse. 
Feb 08 20:52:51 taskcluster-github app/worker.1: Thu, 09 Feb 2017 01:52:51 GMT taskcluster-github:github-auth Authenticated as installation: 9216 
Feb 08 20:52:51 taskcluster-github app/worker.1: Thu, 09 Feb 2017 01:52:51 GMT taskcluster-github:handlers:764bc500-ee6a-11e6-868f-1e43848cab97 Trying to get commit info in job handler... 
Feb 08 20:52:51 taskcluster-github app/worker.1: Thu, 09 Feb 2017 01:52:51 GMT taskcluster-github:handlers Error (reported to sentry) while calling job handler: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"} 
```

**Comment by djmitche** [comment]
So this 404 is from `instGithub.repos.getShaOfCommitRef`, probably because of a "double push" where the sha mentioned in the event has been superseded before we get around to looking for it:
```
$ git push
$ vim foo.py # oops!!
$ git commit --amend -a
$ git push -f
```

**Comment by djmitche** [comment]
So, this was a release event, for https://github.com/taskcluster/taskcluster-worker/releases/tag/v0.0.8 -- and the 404 not found was for ref `tags/v0.0.8`.  That tag exists now, but maybe didn't exist at the time?  Or maybe this is the wrong field to be looking at in a release event?  :confused:

**Review by owlishDeveloper — APPROVED** [review]

**Comment by djmitche** [comment]
With help from @owlishDeveloper and playing with the API manually, I figured out that `tags/v0.0.8` is the wrong format for a ref -- it should be `refs/tags/v0.0.8`.

**Pull request merged**
