### PR TITLE
Bug 1232963: bumped taskcluster-base version

### PR DESCRIPTION
**Pull request by petemoore**
Bumped taskcluster-base version to at least same version used in taskcluster-secrets to see if this fixes bug 1232963.

Completely untested ;)

Hoping this will trigger some unit tests, to see if I totally broke things or not... :p

### CODE REVIEW

**Comment by petemoore** [comment]
@jonasfj I'm not quite sure how to fix this. We're getting http 401 in all the tests - I'm guessing the mock auth server behaves differently in newer taskcluster-base releases.

**Comment by jonasfj** [comment]
hmm... I'm not sure... we probably have to run it locally.
Could very well be this:
https://github.com/taskcluster/taskcluster-github/blob/bug1232963/bin/server.js#L67

Supplying `credentials:      cfg.get('taskcluster:credentials'),` means it'll use the old auth method... which won't work anymore. I think that could be the issue..

Try removing that line.

**Comment by jonasfj** [comment]
See:
https://github.com/taskcluster/taskcluster-lib-api/blob/26aa059a7364a58896364e26d3fff00536f1694f/src/api.js#L1444-L1448

Docs are pretty clear on this... you need to remove credentials to use the remote auth thing...

**Comment by jonasfj** [comment]
Not that I'm parfectly sure that'll fix the issue... sorry :)

**Comment by petemoore** [comment]
@jonasfj yay, that did the trick. thanks for the tip!

**Comment by petemoore** [comment]
I'm not even 100% sure this will get stability added, but I hope so.

**Comment by petemoore** [comment]
@jonasfj could you review again? Thanks!

**Comment by jonasfj** [comment]
Looks good to me... `r+`...

Maybe, jake (:dividehex) wants to merge and land it.

**Comment by petemoore** [comment]
@dividehex one for you! :)

**Pull request merged**
