### PR TITLE
[WIP] API to make badges clickable

### PR DESCRIPTION
**Pull request by owlishDeveloper**
First draft of the API function. Not sure how to test this yet, just wanted to show this and get any feedback :)

### CODE REVIEW

**Comment by imbstack** [comment]
This seems quite good so far! Perhaps find places where there is duplicate code between your various api functions and pull them out into shared functions that are easy to test?

**Comment by owlishDeveloper** [comment]
Cool idea! I'll do that, thanks!

**Comment by djmitche** [comment]
(removed review requests pending an update)

**Comment by owlishDeveloper** [comment]
@imbstack  I followed your suggestion and put away the duplicate code:
* looking up the owner ID and authenticating as installation
* finding the status

To be continued :)

**Comment by owlishDeveloper** [comment]
This work is continued in #189

**Pull request closed without merging**
