### PR TITLE
Debugging messages to debug release

### PR DESCRIPTION
**Pull request by owlishDeveloper**
A.S.:  All the review comments from the previous PR are included here.

> Trying to find the reason for intermittent failures of release event handling.
> 
> Handlers seem to be nicely equipped with debugging messages, so I focused on server side:
> 
> intree.js - check to see if YML is being parsed as expected; catch the taskGroupID for releases.
> api.js - check to see if release webhooks arrive and being recognized as such.
> exchanges.js - check to see if webhook payload is being parsed.
> 
> Also added a bit of clarity so that we instantly could see where the message comes from.

### CODE REVIEW

**Review by djmitche — APPROVED** [review]
This looks great -- let's sanity-check on staging and then push to production!

**Comment by djmitche** [comment]
Should we get this landed?

**Comment by owlishDeveloper** [comment]
Let me check in staging one more time

**Comment by owlishDeveloper** [comment]
@djmitche Yeah, we can now have this landed, ty!

**Pull request merged**
