### PR TITLE
Bug 1476452 - apply defaults for taskGroupId, taskId

### PR DESCRIPTION
**Pull request by djmitche**

### CODE REVIEW

**Comment by djmitche** [comment]
This adds some tests for `tc-yaml.js`, too.  At least for the part I changed :)

**Review by owlishDeveloper — APPROVED** [review]
Looks very good to me!

**Comment by owlishDeveloper** [comment]
(Not sure if related... What is happening to the recent builds? Seems to be a problem with task group id?)

**Comment by djmitche** [comment]
I think it is related :)

**Comment by djmitche** [comment]
released

**Pull request merged**
